plugins {
    // Plugins automatically generated by MLGradleWriter.kt
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
}

val ffmpegEnabled = providers.gradleProperty("recapflow.ffmpeg.enabled")
    .map(String::toBoolean)
    .orElse(false)

val compositionPreviewEnabled = providers.gradleProperty("recapflow.composition.preview.enabled")
    .map(String::toBoolean)
    .orElse(true)

val crossfadeRuntimeSpikeEnabled = providers.gradleProperty("recapflow.crossfade.runtime.enabled")
    .map(String::toBoolean)
    .orElse(false)

val nativeBuildStagingDirectory = file(
    "${System.getProperty("user.home")}/.recapflow/cxx/${rootProject.name}/${project.name}",
)

android {
    namespace = "com.recapflow.ai"
    compileSdk = 36
    ndkVersion = "24.0.8215888"

    defaultConfig {
        applicationId = "com.recapflow.ai"
        minSdk = 28
        targetSdk = 34
        versionCode = 1
        versionName = "1.0-phase6f2.8.1"

        ndk {
            abiFilters += "arm64-v8a"
        }

        buildConfigField(
            "boolean",
            "ENABLE_COMPOSITION_PLAYER_PREVIEW",
            compositionPreviewEnabled.get().toString(),
        )
        buildConfigField(
            "boolean",
            "ENABLE_CROSSFADE_RUNTIME_SPIKE",
            crossfadeRuntimeSpikeEnabled.get().toString(),
        )

        externalNativeBuild {
            cmake {
                arguments += "-DRECAPFLOW_ENABLE_FFMPEG=${if (ffmpegEnabled.get()) "ON" else "OFF"}"
            }
        }
    }

    buildFeatures {
        viewBinding = true
        buildConfig = true
    }

    externalNativeBuild {
        cmake {
            path = file("src/main/cpp/CMakeLists.txt")
            version = "3.18.1"
            // Android shared storage can cause Ninja timestamp rebuild loops.
            buildStagingDirectory = nativeBuildStagingDirectory
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlin {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget("17"))
        }
    }
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.appcompat)
    implementation(libs.material)
    implementation(libs.androidx.constraintlayout)
    implementation(libs.androidx.activity.ktx)
    implementation(libs.androidx.media3.common)
    implementation(libs.androidx.media3.effect)
    implementation(libs.androidx.media3.exoplayer)
    implementation(libs.androidx.media3.ui)
    implementation(libs.androidx.media3.transformer)
    testImplementation(kotlin("test"))
}
