import java.util.Properties

plugins {
    // Plugins automatically generated by MLGradleWriter.kt
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
}

// Release signing is optional so a developer can produce an installable release build before a
// real keystore exists. When keystore.properties is absent the release variant is signed with the
// debug key, which is fine for local testing but is NOT publishable. The build says so loudly.
val keystoreProperties = Properties()
val keystorePropertiesFile = rootProject.file("keystore.properties")
if (keystorePropertiesFile.exists()) {
    keystorePropertiesFile.inputStream().use { keystoreProperties.load(it) }
}
val releaseKeystorePath = keystoreProperties.getProperty("storeFile")
val hasReleaseKeystore = !releaseKeystorePath.isNullOrBlank()

val ffmpegEnabled = providers.gradleProperty("recapflow.ffmpeg.enabled")
    .map(String::toBoolean)
    .orElse(false)

val compositionPreviewEnabled = providers.gradleProperty("recapflow.composition.preview.enabled")
    .map(String::toBoolean)
    .orElse(true)

val crossfadeRuntimeSpikeEnabled = providers.gradleProperty("recapflow.crossfade.runtime.enabled")
    .map(String::toBoolean)
    .orElse(false)

val nativeBuildStagingDirectory = file(
    "${System.getProperty("user.home")}/.recapflow/cxx/${rootProject.name}/${project.name}",
)

android {
    namespace = "com.recapflow.ai"
    compileSdk = 36
    ndkVersion = "24.0.8215888"

    defaultConfig {
        applicationId = "com.recapflow.ai"
        minSdk = 28
        targetSdk = 34
        versionCode = 1
        versionName = "1.0-phase6ux2"

        ndk {
            abiFilters += "arm64-v8a"
        }

        buildConfigField(
            "boolean",
            "ENABLE_COMPOSITION_PLAYER_PREVIEW",
            compositionPreviewEnabled.get().toString(),
        )
        buildConfigField(
            "boolean",
            "ENABLE_CROSSFADE_RUNTIME_SPIKE",
            crossfadeRuntimeSpikeEnabled.get().toString(),
        )

        externalNativeBuild {
            cmake {
                arguments += "-DRECAPFLOW_ENABLE_FFMPEG=${if (ffmpegEnabled.get()) "ON" else "OFF"}"
            }
        }
    }

    buildFeatures {
        viewBinding = true
        buildConfig = true
    }

    externalNativeBuild {
        cmake {
            path = file("src/main/cpp/CMakeLists.txt")
            version = "3.18.1"
            // Android shared storage can cause Ninja timestamp rebuild loops.
            buildStagingDirectory = nativeBuildStagingDirectory
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlin {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget("17"))
        }
    }

    signingConfigs {
        if (hasReleaseKeystore) {
            create("release") {
                storeFile = file(releaseKeystorePath!!)
                storePassword = keystoreProperties.getProperty("storePassword")
                keyAlias = keystoreProperties.getProperty("keyAlias")
                keyPassword = keystoreProperties.getProperty("keyPassword")
            }
        }
    }

    buildTypes {
        getByName("debug") {
            // Keep the debug id distinct from a real release install so both can sit on a device.
            applicationIdSuffix = ".debug"
            versionNameSuffix = "-debug"
        }

        getByName("release") {
            isMinifyEnabled = true
            isShrinkResources = true
            isDebuggable = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro",
            )
            signingConfig = if (hasReleaseKeystore) {
                signingConfigs.getByName("release")
            } else {
                logger.warn(
                    "RecapFlowAI: keystore.properties is missing, so the release variant is " +
                        "signed with the DEBUG key. Installable for local testing, but not " +
                        "publishable. Create keystore.properties before any store release.",
                )
                signingConfigs.getByName("debug")
            }
        }
    }
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.appcompat)
    implementation(libs.material)
    implementation(libs.androidx.constraintlayout)
    implementation(libs.androidx.drawerlayout)
    implementation(libs.androidx.activity.ktx)
    implementation(libs.androidx.media3.common)
    implementation(libs.androidx.media3.effect)
    implementation(libs.androidx.media3.exoplayer)
    implementation(libs.androidx.media3.ui)
    implementation(libs.androidx.media3.transformer)
    testImplementation(kotlin("test"))
}
